definitions:
  workflow: &base_workflow
    environment:
      xcode: 16.2
    triggering:
      events:
        - push
        - pull_request
        - tag
    when:
      changeset:
        excludes:
          - "**/*.md"
    scripts:
      - name: Install Ruby Bundler
        script: gem install bundler:2.3.11
      - name: Install Ruby Gems
        script: bundle install
      - name: Install Arkana
        script: bundle exec arkana -e ./env/.env
      - name: Install Pods
        script: bundle exec pod install
      - name: Build project
        script: |
          set -eo pipefail
          time xcodebuild clean build -workspace Mastodon.xcworkspace \
          -scheme Mastodon \
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

workflows:
  mastodon-ios-m2:
    <<: *base_workflow
    name: Mastodon iOS Build Workflow M2 Mac Mini
    # instance_type: mac_mini_m1
  mastodon-ios-m2-studio:
    <<: *base_workflow
    name: Mastodon iOS Build Workflow M2 Studio Max
  mastodon-ios-m4:
    <<: *base_workflow
    name: Mastodon iOS Build Workflow M4 Mac Mini
  mastodon-ios-m4-pro:
    <<: *base_workflow
    name: Mastodon iOS Build Workflow M4 Pro Mac Mini
    # instance_type: mac_mini_m2
